version: '3.8'

services:
  user-service:
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=dev
    networks:
      - app-network

  notification-service:
    build:
      context: ./backend/notification-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-network
  
  news-service:
    build:
      context: ./backend/news-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    networks:
      - app-network

  
  dapr:
    image: "daprio/daprd:latest"
    container_name: dapr
    command: ["./daprd", "-app-id", "user-service", "-app-port", "3000", "-dapr-http-port", "3500", "-dapr-grpc-port", "50002", "-components-path", "/components"]
    volumes:
      - "./backend/components:/components"
    depends_on:
      - user-service
      - redis
    networks:
      - app-network
    ports:
      - "3500:3500"
      - "50002:50002"

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  react-app:
    build:
      context: ./frontend/react-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/react-app/src:/app/src
    networks:
      - app-network

networks:
  app-network:
    driver: bridge